version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errorlint
    - nilerr
    - bodyclose
    - unparam
    - errcheck

  exclusions:
    rules:
      - path: '.*_test\.go'
        linters:
          - errcheck
          - unparam
          - bodyclose

formatters:
  enable:
    - gofmt
    - goimports
