version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # v2 replacement for "disable-all: true"
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errorlint
    - nilerr
    - bodyclose
    - unparam
    - errcheck

  # v2 way to exclude issues by path / per-linter
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
          - unparam
          - bodyclose

formatters:
  enable:
    - gofmt
    - goimports
