version: 2

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # Bugs reales
    - govet
    - staticcheck
    - ineffassign
    - errorlint
    - nilerr
    - bodyclose
    - unparam
    - errcheck

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-use-default: false

  exclude-rules:
    # Tests: no romper por defers, mocks, etc.
    - path: _test\.go
      linters:
        - errcheck
        - unparam
        - bodyclose
